version: '3.8'

services:
  django:
    build: .
    entrypoint: ./entrypoint.sh
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 1s
      timeout: 5s
      retries: 10
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 5s
      retries: 10
    env_file: .env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


  celery_worker:
    build: .
    command: celery -A core worker --loglevel=info
    env_file: .env
    depends_on:
      - django
      - redis
      - postgres

  celery_beat:
    build: .
    command: celery -A core beat --loglevel=info
    env_file: .env
    depends_on:
      - django
      - redis
      - postgres

volumes:
  postgres_data:
  redis_data:
