# Generated by Django 5.0 on 2023-12-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_web3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
