# Generated by Django 5.0 on 2023-12-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_web3', '0002_alter_event_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tx_hash',
            field=models.CharField(max_length=66, unique=True),
        ),
    ]
