# Generated by Django 5.0 on 2023-12-26 11:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_web3', '0003_alter_event_tx_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='EthAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True)),
                ('nonce', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
